version: '3'
services:
  kubishi-dev: 
    image: registry.digitalocean.com/kubishi-registry/kubishi-sentences:latest
    volumes:
      - .env:/app/.env
    ports:
      - "5000:5000"
    command: python app.py
